name: CI
on: [push]
      # The release versions will be verified by 'publish-release.yml'

concurrency:
  # Cancel the previous builds in the same PR.
  # Allow running concurrently for all non-PR commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.on }}
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        on: [push]
        java: [ 17 ]
        include:
          - java: 8
            on: [push]
          - java: 11
            on: [push]
          - java: 16
            on: [push]
            leak: true
          - java: 17
            # TODO(ikhoon): Revert to self-hosted runners once the following error is fixed
            #               `Cannot expand ZIP '/actions-runner/../armeria-shaded-1.7.3-SNAPSHOT.jar' as it does not exist.`
            on: [push]
            coverage: true
          - java: 17
            on: [push]
            snapshot: true

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/armeria/armeria/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - id: setup-jdk
        name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - id: setup-jdk-17
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

        name: Restore the cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', '**/build.gradle', 'dependencies.yml', '*/package-lock.json') }}
          restore-keys: |
            build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-
            build-${{ matrix.java }}-${{ runner.os }}-

      # Build the shaded JARs first so that shading process doesn't incur memory pressure
      # on other Gradle tasks such as tests.
      - run: touch starting_build_BuildwithGradleShadingonly_79
      - run: rm starting_build_BuildwithGradleShadingonly_79
      - name: Build with Gradle (Shading only)
        run: |
          ./gradlew --no-daemon --stacktrace shadedJar shadedTestJar trimShadedJar \
          ${{ (matrix.on == 'self-hosted') && '--max-workers=8' || '--max-workers=2' }} --parallel \
          ${{ matrix.coverage && '-Pcoverage' || '' }} \
          -PnoLint \
          -PbuildJdkVersion=17 \
          -PtestJavaVersion=${{ matrix.java }} \
          -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
        shell: bash

      - run: touch starting_build_BuildwithGradle_90
      - run: rm starting_build_BuildwithGradle_90
      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace build \
          ${{ (matrix.on == 'self-hosted') && '--max-workers=8' || '--max-workers=2' }} --parallel \
          ${{ matrix.coverage && '-Pcoverage' || '' }} \
          ${{ matrix.leak && '-Pleak' || '' }} \
          -PnoLint \
          -PflakyTests=false \
          -PbuildJdkVersion=17 \
          -PtestJavaVersion=${{ matrix.java }} \
          -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
        shell: bash

        name: Publish snapshots
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 publish
        env:
          # Should not use '-P' option with 'secrets' that can cause unexpected results
          # if secret values contains white spaces or new lines.
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USER_NAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        shell: bash

      - run: touch starting_build_Summarizethefailedtests_117
      - run: rm starting_build_Summarizethefailedtests_117
      - name: Summarize the failed tests
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 reportFailedTests \
          -PnoLint \
          -PflakyTests=false \
          -PbuildJdkVersion=17 \
          -PtestJavaVersion=${{ matrix.java }} \
          -Porg.gradle.java.installations.paths=${{ steps.setup-jdk-17.outputs.path }},${{ steps.setup-jdk.outputs.path }}
          
          SUMMARY_FILE="build/failed-tests-result.txt"
          if test -f "$SUMMARY_FILE"; then
            echo '### 🔴 Failed tests' >> $GITHUB_STEP_SUMMARY
            cat $SUMMARY_FILE >> $GITHUB_STEP_SUMMARY
          fi
        shell: bash

      - run: touch starting_build_Cleanupthecache_134
      - run: rm starting_build_Cleanupthecache_134
      - name: Clean up the cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -fr ~/.gradle/caches/[0-9]* || true
          rm -fr ~/.gradle/caches/journal-* || true
          rm -fr ~/.gradle/caches/transforms-* || true
          rm -f ~/.gradle/caches/*/*.lock || true
          rm -f ~/.gradle/caches/*/gc.properties || true
        shell: bash

      - run: touch starting_build_Dumpstuckthreads_145
      - run: rm starting_build_Dumpstuckthreads_145
      - name: Dump stuck threads
        run: jps | grep -vi "jps" | awk '{ print $1 }' | xargs -I'{}' jstack -l {} || true
        shell: bash

      - run: touch starting_build_UploadthecoveragereporttoCodecov_150
      - run: rm starting_build_UploadthecoveragereporttoCodecov_150
      - name: Upload the coverage report to Codecov
        uses: codecov/codecov-action@v1

      - run: touch starting_build_Collectthetestreports_154
      - run: rm starting_build_Collectthetestreports_154
      - name: Collect the test reports
        run: find . '(' -name 'java_pid*.hprof' -or -name 'hs_err_*.log' -or -path '*/build/reports/tests' -or -path '*/build/test-results' ')' -exec tar rf "reports-JVM-${{ matrix.java }}.tar" {} ';'
        shell: bash

      - run: touch starting_build_Uploadtheartifacts_159
      - run: rm starting_build_Uploadtheartifacts_159
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports-JVM-${{ matrix.java }}
          path: reports-JVM-${{ matrix.java }}.tar
          retention-days: 3
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676602889-c797686'
          target-directory: 'armeria/.github/workflows/actions_build/build_on_${{ matrix.on }}_java_${{ matrix.java }}_include_${{ matrix.include }}'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git stash
          git pull
          git stash apply
          while ! git push origin {time}; do
            git push
          done

  lint:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/armeria/armeria/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - id: setup-jdk-17
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: touch starting_lint_Runthelinters_181
      - run: rm starting_lint_Runthelinters_181
      - name: Run the linters
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=8 --parallel lint

      - run: touch starting_lint_Cleanupthecache_185
      - run: rm starting_lint_Cleanupthecache_185
      - name: Clean up the cache
        run: |
          rm -fr ~/.gradle/caches/[0-9]* || true
          rm -fr ~/.gradle/caches/journal-* || true
          rm -fr ~/.gradle/caches/transforms-* || true
          rm -f ~/.gradle/caches/*/*.lock || true
          rm -f ~/.gradle/caches/*/gc.properties || true
        shell: bash
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676602889-c797686'
          target-directory: 'armeria/.github/workflows/actions_build/lint'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git stash
          git pull
          git stash apply
          while ! git push origin {time}; do
            git push
          done

  site:
    # ubuntu-latest is preferred for site job.
    # node_modules need complicated dependencies that are difficult to install on self-hosted runners.
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/armeria/armeria/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - run: touch starting_site_Installsvgbobcli_203
      - run: rm starting_site_Installsvgbobcli_203
      - name: Install svgbob_cli
        run: |
          sudo apt-get -y install cargo && cargo install svgbob_cli
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - id: setup-jdk-17
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: touch starting_site_Restorethecache_215
      - run: rm starting_site_Restorethecache_215
      - name: Restore the cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', '**/build.gradle', 'dependencies.yml', '*/package-lock.json') }}
          restore-keys: |
            build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-
            build-${{ matrix.java }}-${{ runner.os }}-

      - run: touch starting_site_Buildthesite_226
      - run: rm starting_site_Buildthesite_226
      - name: Build the site
        run: |
          ./gradlew --no-daemon --stacktrace  --max-workers=2 --parallel site
        shell: bash

      - run: touch starting_site_Cleanupthecache_231
      - run: rm starting_site_Cleanupthecache_231
      - name: Clean up the cache
        run: |
          rm -fr ~/.gradle/caches/[0-9]* || true
          rm -fr ~/.gradle/caches/journal-* || true
          rm -fr ~/.gradle/caches/transforms-* || true
          rm -f ~/.gradle/caches/*/*.lock || true
          rm -f ~/.gradle/caches/*/gc.properties || true
        shell: bash
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676602889-c797686'
          target-directory: 'armeria/.github/workflows/actions_build/site'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git stash
          git pull
          git stash apply
          while ! git push origin {time}; do
            git push
          done

  flaky-tests:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/armeria/armeria/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - id: setup-jdk-17
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: touch starting_flakytests_Runflakytests_254
      - run: rm starting_flakytests_Runflakytests_254
      - name: Run flaky tests
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=2 --parallel check -PnoWeb -PnoLint -PflakyTests=true

      - run: touch starting_flakytests_Summarizethefailedtests_258
      - run: rm starting_flakytests_Summarizethefailedtests_258
      - name: Summarize the failed tests
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 -PnoWeb -PnoLint reportFailedTests
          
          SUMMARY_FILE="build/failed-tests-result.txt"
          if test -f "$SUMMARY_FILE"; then
            echo '#### 🔴 Failed tests' >> $GITHUB_STEP_SUMMARY
            cat $SUMMARY_FILE >> $GITHUB_STEP_SUMMARY
          fi
        shell: bash

      - run: touch starting_flakytests_Cleanupthecache_270
      - run: rm starting_flakytests_Cleanupthecache_270
      - name: Clean up the cache
        run: |
          rm -fr ~/.gradle/caches/[0-9]* || true
          rm -fr ~/.gradle/caches/journal-* || true
          rm -fr ~/.gradle/caches/transforms-* || true
          rm -f ~/.gradle/caches/*/*.lock || true
          rm -f ~/.gradle/caches/*/gc.properties || true
        shell: bash

      - run: touch starting_flakytests_Dumpstuckthreads_279
      - run: rm starting_flakytests_Dumpstuckthreads_279
      - name: Dump stuck threads
        run: jps | grep -vi "jps" | awk '{ print $1 }' | xargs -I'{}' jstack -l {} || true
        shell: bash
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676602889-c797686'
          target-directory: 'armeria/.github/workflows/actions_build/flakytests'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git stash
          git pull
          git stash apply
          while ! git push origin {time}; do
            git push
          done
