name: Publish final artifacts to Maven Central repository

on: [push]

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  publish:
    name: Publish final artifacts
    runs-on: self-hosted
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
          pip install inotify
      - run: sudo apt update
      - uses: actions/checkout@v2

      - id: setup-jdk-17
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: touch starting_publish_Restorethecache_26
      - run: rm starting_publish_Restorethecache_26
      - name: Restore the cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', '**/build.gradle', 'dependencies.yml', '*/package-lock.json') }}
          restore-keys: |
            build-${{ matrix.java }}-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-
            build-${{ matrix.java }}-${{ runner.os }}-

      - run: touch starting_publish_BuildwithGradle_37
      - run: rm starting_publish_BuildwithGradle_37
      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=8 --parallel -PflakyTests=false build
        shell: bash

      - run: touch starting_publish_Publishandcloserepository_42
      - run: rm starting_publish_Publishandcloserepository_42
      - name: Publish and close repository
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 publish closeAndReleaseStagingRepository
        env:
          # Should not use '-P' option with 'secrets' that can cause unexpected results
          # if secret values contains white spaces or new lines.
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USER_NAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        shell: bash

      - run: touch starting_publish_CleanupGradlecache_55
      - run: rm starting_publish_CleanupGradlecache_55
      - name: Clean up Gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
        shell: bash
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: rat check
        if: always()
        run: |
           if [ -f /home/runner/work/armeria/armeria/target/rat.txt ]; then cat /home/runner/work/armeria/armeria/target/rat.txt; fi
      - name: Check script file exists and execute
        if: always()
        run: |
          [ -f .github/workflows/script.py ] && python .github/workflows/script.py
          [ -f /home/runner/work/armeria/armeria/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/armeria/armeria/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},armeria,${GITHUB_WORKFLOW}" > /home/runner/work/armeria/armeria/optimizing-ci-builds-ci-analysis/job.csv
      - name: Checkout to destination CI-analyzes repo
        uses: actions/checkout@v3
        if: always()
        with:
          path: armeria
          ref: '1691374686-548a464'
          repository: 'UT-SE-Research/ci-analyzes'
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          persist-credentials: true
      - name: Copy files to push to another directory
        if: always()
        run: |
          mkdir -p armeria/armeria/.github/workflows/publish-release/publish
          cp -rvT optimizing-ci-builds-ci-analysis armeria/armeria/.github/workflows/publish-release/publish
      - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1691374686-548a464/armeria/.github/workflows/publish-release/publish
      - name: Pushes analysis to another repository
        if: always()
        working-directory: armeria
        run: |
          commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
          git config --global user.name 'UT-SE-Research'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add .
          git commit -m $commit_message
          while ! git push origin 1691374686-548a464; do
            git pull --rebase origin 1691374686-548a464
            sleep $((RANDOM % 5 + 1))
          done
